@echo off
cd /d E:\Webhelen\Sites\yushangw
echo Removing inherited template content...
git rm -r -q "_data/comments"
git rm -r -q "_drafts"
git rm -r -q "_includes/comments-providers"
git rm -r -q "_includes/footer"
git rm -r -q "_posts"
git rm -r -q "_publications"
git rm -r -q "_research"
git rm -r -q "_source"
git rm -r -q "data"
git rm -r -q "files/html"
git rm -r -q "images/posts"
git rm -r -q "images/teaching"
git rm -r -q "markdown_generator"
git rm -r -q "talkmap"
git rm -q "CHANGELOG.md"
git rm -q "CNAME"
git rm -q "CONTRIBUTING.md"
git rm -q "Gemfile.lock"
git rm -q "Website.Rproj"
git rm -q "_data/authors.yml"
git rm -q "_includes/archive-single-cv.html"
git rm -q "_includes/archive-single-talk-cv.html"
git rm -q "_includes/archive-single-talk.html"
git rm -q "_includes/comment.html"
git rm -q "_includes/comments.html"
git rm -q "_includes/feature_row"
git rm -q "_includes/gallery"
git rm -q "_includes/paginator.html"
git rm -q "_includes/post_pagination.html"
git rm -q "_layouts/single-portfolio.html"
git rm -q "_layouts/splash.html"
git rm -q "_layouts/talk.html"
git rm -q "_pages/posts.html"
git rm -q "_pages/publications.md"
git rm -q "_pages/sitemap.md"
git rm -q "_pages/tag-archive.html"
git rm -q "_pages/talkmap.html"
git rm -q "_pages/talks.html"
git rm -q "_pages/terms.md"
git rm -q "assets/css/collapse.css"
git rm -q "assets/js/collapse.js"
git rm -q "files/paper1.pdf"
git rm -q "files/paper2.pdf"
git rm -q "files/paper3.pdf"
git rm -q "files/pdf/research/Agreement Strength SI.pdf"
git rm -q "files/pdf/research/Agreement Strength.pdf"
git rm -q "files/pdf/research/BayesPostEst.pdf"
git rm -q "files/pdf/research/Measuring Agreements in Civil War SI.pdf"
git rm -q "files/pdf/research/Measuring Agreements in Civil War.pdf"
git rm -q "files/pdf/research/PKO Targeting.pdf"
git rm -q "files/pdf/research/PSS 2018 Poster.pdf"
git rm -q "files/pdf/research/PolMeth 2018 Poster.pdf"
git rm -q "files/pdf/research/PolMeth 2019 Poster.pdf"
git rm -q "files/pdf/research/Terrorism Territorial Aggression.pdf"
git rm -q "files/pdf/research/Turning the Lights on SI.pdf"
git rm -q "files/pdf/research/Turning the Lights on.pdf"
git rm -q "files/pdf/research/UNPoC.pdf"
git rm -q "files/pdf/research/Under the Roof of Rebels SI.pdf"
git rm -q "files/pdf/research/Under the Roof of Rebels.pdf"
git rm -q "files/pdf/research/Unsettled_Borders.pdf"
git rm -q "files/pdf/teaching-materials/281 1-15.pdf"
git rm -q "files/pdf/teaching-materials/281 1-22.pdf"
git rm -q "files/pdf/teaching-materials/281 1-24_R_Scripts.pdf"
git rm -q "files/pdf/teaching-materials/281 2-5_Hockey.pdf"
git rm -q "files/pdf/teaching-materials/3090 1-27.pdf"
git rm -q "files/pdf/teaching-materials/3090 1-29.pdf"
git rm -q "files/pdf/teaching-materials/3171 9-10.pdf"
git rm -q "images/bio-photo-2.jpg"
git rm -q "images/bio-photo.jpg"
git rm -q "images/research/Agreement-Strength.png"
git rm -q "images/research/ecdf.png"
git rm -q "images/research/epr.png"
git rm -q "images/research/gp-bma.png"
git rm -q "images/research/map.png"
git rm -q "images/research/spatial_weighting.png"
git rm -q "images/research/ternary.png"
echo Staging updated files...
git add -A
git status --short | find /c /v "" 
echo.
echo Review the list above, then run:
echo   git commit -m "Remove inherited template content, fix URLs and images, compress photos"
echo   git push
